# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICBI @ SIAT 
name: ICBI @ SIAT
email: zhoupc1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Google search results) and in your feed.xml site description.
baseurl: ""
baidutmid: 5a3c43adc0220a5563ef1dcaec6ab720
# url: https://icbi-siat.github.io/

# Company Information
company_name: Shenzhen Institutes of Advanced Technology, Chinese Academy of Sciences
address_line: 1068 Xueyuan Avenue, Shenzhen University Town, Nanshan District, Shenzhen, China 518055
telephone_number: +86.755.0000.0000
fax_number: +86.755.0000.0000
company_email: icbi_hr__at__siat.ac.cn
google_map: https://goo.gl/maps/DZ2ryodVVL6DRswy5 

# markdown: redcarpet
# permalink: /:categories/:title/
# future: true

# tracking (by Fang)


include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

